## Matrix Multiplication

In [9]:
from numpy import array, shape, empty

In [19]:
A = array([[1,2,0],
           [1,1,0],
           [0,1,1]],)

B = array([[2,1,1],
           [2,0,1],
           [0,2,1]])

A1 = array([[1,2,3]])
B1 = array([[1],
            [2],
            [3]])

def dotproduct(A, B):
    '''
    returns: dot product of matrices A and B with shape [i,j]
    '''
    i,k = shape(A) # rows 
    j = shape(B)[1] # cols
    product = empty(i*j).reshape(i, j) # initialize empty matrix
    
    for row in range(i): 
        for col in range(j): 
            product[row,col] = sum([A[row,k]*B[k,col] for k in range(k)])
            # vector multiplication and summation
    
    return product

print(f'{dotproduct(A,B)}\n\n{dotproduct(A1,B1)}')

[[6. 1. 3.]
 [4. 1. 2.]
 [2. 2. 2.]]

[[14.]]
